name: Python application
on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout actions
    - uses: actions/checkout@v1
    - name: date -R
      run: |
        date -R

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        
    - name: test pytest
      run: |
        cd pytest
        python test.py

